Trying to build game
Getting the errors:
-Assets\Scripts\Camera Scripts\CameraControlTrigger.cs(83,30): error CS0246: The type or namespace name 'Editor' could not be found (are you missing a using directive or an assembly reference?)
-Assets\Scripts\Camera Scripts\CameraControlTrigger.cs(82,2): error CS0246: The type or namespace name 'CustomEditorAttribute' could not be found (are you missing a using directive or an assembly reference?)
-Assets\Scripts\Camera Scripts\CameraControlTrigger.cs(82,2): error CS0246: The type or namespace name 'CustomEditor' could not be found (are you missing a using directive or an assembly reference?)
-Assets\Scripts\Camera Scripts\CameraControlTrigger.cs(93,26): error CS0115: 'MyUnityEditor.OnInspectorGUI()': no suitable method found to override